package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, CARACTER, CADENA_CARACTERES, OPERADOR_INCREMENTO, OPERADOR_DECREMENTO, IDENTIFICADOR,
    PALABRA_RESERVADA, COMENTARIO_BLOQUE, COMENTARIO_LINEA, OPERADOR_LOGICO, OPERADOR_ARITMETICO,OPERADOR_ASIGNACION,
    OPERADOR_RELACIONAL, PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO, CORCHETE_IZQUIERDO, CORCHETE_DERECHO,
    LLAVE_IZQUIERDA, LLAVE_DERECHA, SEPARADOR, FIN_SENTENCIA, PUNTO, DESCONOCIDO
}